// Command benchrunner measures how ledgers arrive from a ledger source, to
// answer the question this prototype exists for: does streaming raw ledgers off
// another machine stay inside the local-pipe envelope RPC v2 ingest budgets for
// (Phase 3: 80 ms per ledger, all of ingest)?
//
//	# zero-dependency demo: synthetic server and client in one process
//	benchrunner --mode loopback
//
//	# against a running corestreamd
//	benchrunner --mode remote --url ws://box:8462 --start 55000000 --end 55001000 --csv run.csv
//
//	# the local baseline: captive core in this process, no network
//	benchrunner --mode local --start 55000000 --end 55001000 \
//	  --core-config ./captive-core.cfg --history-archive-urls https://history.stellar.org/...
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"math"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/stellar/go-stellar-sdk/ingest/ledgerbackend"
	supportlog "github.com/stellar/go-stellar-sdk/support/log"

	"github.com/stellar/remote-core-poc/internal/server"
	"github.com/stellar/remote-core-poc/internal/store"
	"github.com/stellar/remote-core-poc/remoteledger"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "benchrunner: %v\n", err)
		os.Exit(1)
	}
}

type options struct {
	mode  string
	url   string
	start uint
	end   uint
	csv   string

	syntheticSize     int
	syntheticInterval time.Duration
	count             uint
	buffer            int
	verify            bool

	coreBinary        string
	coreConfig        string
	historyArchiveURL string
	storageDir        string
	networkPassphrase string
}

// parseFlags reads args, writing usage and flag errors to out.
func parseFlags(out io.Writer, args []string) (options, error) {
	var o options
	fs := flag.NewFlagSet("benchrunner", flag.ContinueOnError)
	fs.SetOutput(out)
	fs.StringVar(&o.mode, "mode", "loopback", "loopback|remote|local")
	fs.StringVar(&o.url, "url", "ws://127.0.0.1:8462", "corestreamd URL (remote mode)")
	fs.UintVar(&o.start, "start", 0, "first ledger (0 = tip in remote mode)")
	fs.UintVar(&o.end, "end", 0, "last ledger (0 = unbounded)")
	fs.StringVar(&o.csv, "csv", "", "write per-ledger rows to this file")

	fs.IntVar(&o.syntheticSize, "synthetic-size", server.DefaultSyntheticSize, "loopback: ledger payload bytes")
	fs.DurationVar(&o.syntheticInterval, "synthetic-interval", 10*time.Millisecond, "loopback: ledger close interval")
	fs.UintVar(&o.count, "count", 100, "loopback: ledgers to stream")
	fs.IntVar(&o.buffer, "buffer", server.DefaultSubscriberBuffer, "loopback: per-subscriber queue depth")
	fs.BoolVar(&o.verify, "verify", false, "loopback: check every payload against the regenerated bytes")

	fs.StringVar(&o.coreBinary, "core-binary", "", "local: stellar-core binary (default: found on PATH)")
	fs.StringVar(&o.coreConfig, "core-config", "", "local: captive-core toml path")
	fs.StringVar(&o.historyArchiveURL, "history-archive-urls", "", "local: comma-separated history archive URLs")
	fs.StringVar(&o.storageDir, "storage-dir", "", "local: captive core storage path")
	fs.StringVar(&o.networkPassphrase, "network-passphrase", "", "local: override the toml's NETWORK_PASSPHRASE")

	if err := fs.Parse(args); err != nil {
		return o, err
	}
	if fs.NArg() > 0 {
		return o, fmt.Errorf("unexpected argument %q", fs.Arg(0))
	}
	if uint64(o.start) > math.MaxUint32 || uint64(o.end) > math.MaxUint32 || uint64(o.count) > math.MaxUint32 {
		return o, errors.New("--start, --end and --count must fit in a ledger sequence")
	}
	if o.end != 0 && o.start > o.end {
		return o, fmt.Errorf("--end %d is before --start %d", o.end, o.start)
	}
	switch o.mode {
	case "loopback":
		if o.count == 0 {
			return o, errors.New("--count must be positive in loopback mode")
		}
	case "remote":
	case "local":
		if o.start == 0 {
			return o, errors.New("--start is required in local mode: captive core replays a known range")
		}
		if o.coreConfig == "" {
			return o, errors.New("--core-config is required in local mode")
		}
		if o.historyArchiveURL == "" {
			return o, errors.New("--history-archive-urls is required in local mode")
		}
	default:
		return o, fmt.Errorf("--mode must be loopback, remote or local, got %q", o.mode)
	}
	return o, nil
}

func run() error {
	o, err := parseFlags(os.Stderr, os.Args[1:])
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	var c *collector
	switch o.mode {
	case "loopback":
		c, err = runLoopback(ctx, o)
	case "remote":
		c, err = runRemote(ctx, o, o.url)
	case "local":
		c, err = runLocal(ctx, o)
	}
	if c != nil {
		fmt.Print(c.summary())
		if o.csv != "" {
			if werr := writeCSVFile(o.csv, c); werr != nil {
				err = errors.Join(err, werr)
			} else {
				fmt.Printf("csv          %s\n", o.csv)
			}
		}
	}
	return err
}

// runLoopback streams a synthetic corestreamd in this process over 127.0.0.1.
// It needs no core binary, no network and no server to be running, so it doubles
// as the smoke test that the whole path works.
func runLoopback(ctx context.Context, o options) (*collector, error) {
	dir, err := os.MkdirTemp("", "benchrunner-loopback-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(dir)

	ring, err := store.Open(filepath.Join(dir, "ledgers"), int(o.count)+1)
	if err != nil {
		return nil, err
	}
	start := uint32(o.start)
	if start == 0 {
		start = 1
	}
	srv, err := server.New(server.Config{
		Source: server.NewSyntheticStream(server.SyntheticConfig{
			Size:     o.syntheticSize,
			Interval: o.syntheticInterval,
		}),
		Range:            server.SyntheticRange(start, uint32(o.count)),
		Store:            ring,
		SubscriberBuffer: o.buffer,
		// The measurement is what matters here, not the server's narration.
		Logger: slog.New(slog.NewTextHandler(io.Discard, nil)),
	})
	if err != nil {
		return nil, err
	}

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return nil, err
	}
	httpSrv := &http.Server{Handler: srv.Handler()}
	go func() { _ = httpSrv.Serve(ln) }()
	defer func() { _ = httpSrv.Close() }()

	srvCtx, stopSource := context.WithCancel(ctx)
	defer stopSource()
	sourceDone := make(chan error, 1)
	go func() { sourceDone <- srv.Run(srvCtx) }()

	url := "ws://" + ln.Addr().String()
	fmt.Printf("loopback server on %s: %d ledgers of %d bytes every %s\n",
		ln.Addr(), o.count, o.syntheticSize, o.syntheticInterval)

	last := start + uint32(o.count) - 1
	c, err := consume(ctx, "loopback (remoteledger over 127.0.0.1)", url, ledgerbackend.BoundedRange(start, last), o)
	if err != nil {
		return c, err
	}
	stopSource()
	return c, <-sourceDone
}

// runRemote consumes a corestreamd that is already running, which is the
// measurement that matters: the client is the same one RPC ingest would use.
func runRemote(ctx context.Context, o options, url string) (*collector, error) {
	return consume(ctx, "remote (corestreamd over the network)", url, rangeFrom(o), o)
}

func consume(
	ctx context.Context, label, url string, rng ledgerbackend.Range, o options,
) (*collector, error) {
	c := newCollector(label)
	var current uint32
	stream := remoteledger.New(url, remoteledger.WithObserver(func(info remoteledger.LedgerInfo) {
		current = info.Sequence
		delivery, ok := info.Delivery()
		c.add(info.Sequence, info.Size, time.Unix(0, info.ReceivedUnixNano), delivery, ok)
	}))

	expected := make([]byte, o.syntheticSize)
	for raw, err := range stream.RawLedgers(ctx, rng) {
		if err != nil {
			return c, err
		}
		if o.verify {
			server.FillSyntheticPayload(expected, current)
			if len(raw) != len(expected) || string(raw) != string(expected) {
				return c, fmt.Errorf("ledger %d payload does not match the synthetic source", current)
			}
		}
	}
	return c, nil
}

// runLocal consumes captive core in this process: the baseline the remote
// numbers are compared against. Ledgers arrive over a pipe with no emit stamp,
// so this mode reports cadence and throughput, not delivery latency.
func runLocal(ctx context.Context, o options) (*collector, error) {
	storageDir := o.storageDir
	if storageDir == "" {
		dir, err := os.MkdirTemp("", "benchrunner-core-")
		if err != nil {
			return nil, err
		}
		defer os.RemoveAll(dir)
		storageDir = dir
	}
	source, err := server.NewCaptiveSource(ctx, server.CaptiveConfig{
		BinaryPath:         o.coreBinary,
		ConfigPath:         o.coreConfig,
		StoragePath:        storageDir,
		HistoryArchiveURLs: splitURLs(o.historyArchiveURL),
		NetworkPassphrase:  o.networkPassphrase,
	}, supportlog.New())
	if err != nil {
		return nil, err
	}

	c := newCollector("local (captive core in this process)")
	seq := o.start
	for raw, err := range source.RawLedgers(ctx, rangeFrom(o)) {
		if err != nil {
			return c, err
		}
		c.add(uint32(seq), len(raw), time.Now(), 0, false)
		seq++
	}
	return c, nil
}

func rangeFrom(o options) ledgerbackend.Range {
	if o.end != 0 {
		return ledgerbackend.BoundedRange(uint32(o.start), uint32(o.end))
	}
	return ledgerbackend.UnboundedRange(uint32(o.start))
}

func writeCSVFile(path string, c *collector) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	if err := c.writeCSV(f); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

func splitURLs(csv string) []string {
	var urls []string
	for _, u := range strings.Split(csv, ",") {
		if u = strings.TrimSpace(u); u != "" {
			urls = append(urls, u)
		}
	}
	return urls
}
